[package]
name = "Element_wise_Division_Using_AVX2_SIMD_with_F64_Conversion"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "x86_64"] }